### ISSUE TITLE
Unintentional variable assignment in if statement

### ISSUE THREAD

**Issue by dambrogia** [paviliondev/discourse-topic-previews-sidecar#161]
I haven't tested this, but as I was going through the code I believe [this](https://github.com/paviliondev/discourse-topic-previews/blob/master/controllers/thumbnail_selection.rb#L14) is a bug:

As a test I can do the following:

```
x = 'hello'

if x = 'goodbye' || x == 'something-else'
    puts x
end

# Output: 'goodbye'
```

This is because `x` will always be set to `goodbye` and because that OR operator is successful, the if statement will be entered every time. For the scope of the code at hand within this repository, it means that this line will be run every time and also the `current_user.id` is being unintentionally mutated.

          thumbnails = TopicPreviews::ThumbnailSelectionHelper.get_thumbnails_from_topic(topic)

The code should read:

    if current_user.id == user_id || current_user.admin == true

Rather than:

    if current_user.id = user_id || current_user.admin == true

I would be happy to make a PR to fix this.

**Comment by merefield** [comment]
Fixed in #172 thanks for the report
