### ISSUE TITLE
Add featured images to mobile

### ISSUE THREAD

**Issue by merefield** [paviliondev/discourse-topic-previews-sidecar#53]
Add featured images to mobile

**Comment by satashi0123** [comment]
Add featured images to mobile please ^^

**Comment by merefield** [comment]
Hey Satashi, this is now implemented in the TC version:  https://github.com/merefield/discourse-topic-list-previews-theme

See also:  https://meta.discourse.org/t/topic-list-previews/101646/1010?u=merefield

**Comment by merefield** [comment]
Not relevant to sidecar
